services:
  broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  jaeger: 
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"  #ui
      - "6831:6831/udp" #traces UDP 
      - "14268:14268" # traces http
      - "4317:4317"   # OTLP/grppc 
      - "4318:4318" # OTLP/http

  api-gateway: 
    image: kong:3.9
    environment:
      KONG_DATABASE: 'off'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002'
    ports: 
      - "8000:8000" # proxy  ( API )
      - "8001:8001" # API ADMIN ( Admin )
      - "8002:8002" # UI  ( Admin )
      - "8443:8443" # proxy SSL ( https )
      - "8444:8444" # proxy SSL ( https )
       
 
volumes:
  rabbitmq_data: